### ISSUE TITLE
過去k回

### ISSUE THREAD

**Issue by noimin0610** [noimin0610/atcoderapps#2]
過去k回の結果で比較できるようにする
旧Performancesは最大過去20回だけどこの制限も外す

**Comment by fuurin** [comment]
過去k回よりは，20YY/MM/DD以降のデータで統計情報を表示，なんてどうだろう？
過去k回の情報で比較すると，違う時期に参戦していたユーザとは別のコンテストにおける統計を取ってしまう．
例えばnoiminさんは1月～6月まで，6回，fuurinさんは1月~3月まで3回参戦していた場合，
k=3とすると，noiminさんは4,5,6月のデータ，fuurinさんは1,2,3月のデータで比較してしまう．
これはなんだか平等ではない．
入力形式がめんどくさくなるのでは？と思うかもしれないが，ドロップダウンメニューの項目をグラフのx軸(年月日)から持ってくれば良い．
